### ISSUE TITLE
Add Deerfi

### ISSUE THREAD

**Issue by TT1943** [SparkPoolOfficial/eth123.org#11]
Title: Deerfi
Desc: Decentralized Lending Protocol for Uniswap Liquidity Providers
Website: https://deerfi.com
Logo_url: https://images.emojiterra.com/twitter/v13.0/512px/1f98c.png
Tags:  #DEFI #Lending (借贷)

**Comment by zengmi2140** [comment]
感谢提议！该协议当前资金规模太小，暂不考虑添加。
