### ISSUE TITLE
MathWallet

### ISSUE THREAD

**Issue by ericfish** [SparkPoolOfficial/eth123.org#13]
Title: MathWallet
Desc: MathWallet is a multi-platform (mobile/desktop/hardware) universal crypto wallet that enables token storage of 60+ chains including Ethereum, etc.
Website: https://mathwallet.org/
Logo_url: http://medishares.oss-cn-hongkong.aliyuncs.com/logo/math/MathWallet_App_Icon.png
Tags:  wallet

**Comment by zengmi2140** [comment]
感谢您提供的信息！ETH123 暂时只展示以太坊生态的核心钱包，对于区块链行业的全币种钱包，由于数量众多，目前暂不展示。后续若开放展示此类钱包会添加您提交的项目，感谢！
