### ISSUE TITLE
Add DeFiBox

### ISSUE THREAD

**Issue by javascriptDev** [SparkPoolOfficial/eth123.org#15]
Chinese(中文):
Title: DeFiBox
Desc: 一站式DeFi资产和信息聚合平台
Website: https://www.defibox.com/index?utm_source=2177633
Logo_url: https://www.defibox.com/media/cd1be92d-f083-4c79-b10b-2b554dc96e5a.png
Tags:  // 资产管理、数据分析

English(英文):
Title: DeFiBox
Desc: one-stop DeFi asset, data and protocols aggregation platform
Website: https://www.defibox.com/index?utm_source=2177633
Logo_url: https://www.defibox.com/media/cd1be92d-f083-4c79-b10b-2b554dc96e5a.png
Tags:  // asset management, data analysis

**Comment by TerenceLuo** [comment]
产品名称：InsurAce
网站：https ://insurace.io/
标签：保险
徽标：如下

麻烦添加一下，谢谢，代币已经上火币，主网已经上线，首个做跨链保险和IDO保险的项目

INSUR徽标
![image](https://user-images.githubusercontent.com/80372394/119633304-30295200-be44-11eb-8cc4-96777235a5e8.png)
