### ISSUE TITLE
Nethermind

### ISSUE THREAD

**Issue by annaszeszula** [SparkPoolOfficial/eth123.org#16]
Title:Nethermind
Desc:https://docs.nethermind.io/nethermind/v/chinese/
Website:https://nethermind.io/
Logo_url:https://github.com/NethermindEth/nethermind/blob/master/Nethermind.png
Tags:  // eth client 
Please add Nethermind as ETH1 client

**Comment by chahq520** [comment]
> Title:Nethermind
> Desc:https://docs.nethermind.io/nethermind/v/chinese/
> Website:https://nethermind.io/
> Logo_url:https://github.com/NethermindEth/nethermind/blob/master/Nethermind.png
> Tags: // eth client
> Please add Nethermind as ETH1 client
