### ISSUE TITLE
https://profile.tokenpocket.pro/?locale=zh-CN&utm_source=tokenpocket#/token/48603096

### ISSUE THREAD

**Issue by Oscarwong79** [SparkPoolOfficial/eth123.org#17]
Title:
Desc:
Website:
Logo_url:
Tags:  // defi,lottery ..

**Comment by TerenceLuo** [comment]
类型：保险
产品名称：InsurAce
网站：https://insurace.io/
Logo：
麻烦添加一下，谢谢，代币已经上火币，目前有测试网，主网即将上线

![INSUR LOGO](https://user-images.githubusercontent.com/80372394/114979767-0c2a3680-9ebe-11eb-90cc-da901543c0f7.jpg)
