### ISSUE TITLE
Money Movement

### ISSUE THREAD

**Issue by freeyao** [SparkPoolOfficial/eth123.org#2]
Title: Money Movement
Desc: Hosted by Circle Co-Founder and CEO, Jeremy Allaire, The Money Movement is a video series exploring and chronicling the issues and ideas driving this brave new world of digital money.
Website: https://www.circle.com/en/the-money-movement
Logo_url: https://pbcdn1.podbean.com/imglogo/image-logo/8635933/mm-podcast.jpg
Tags:  // defi, podcast

**Comment by zengmi2140** [comment]
已添加，由于desc太长，目前暂不显示。
