### ISSUE TITLE
Taipei Ethereum

### ISSUE THREAD

**Issue by misterioso** [SparkPoolOfficial/eth123.org#5]
Title: Taipei Ethereum 
Desc: 專注在 Ethereum 技術理論、實作、與應用的討論社群，目前每月由社群參加者自願分享。 Ethereum 是具有智慧契約功能的區塊鏈平台。
Website:https://github.com/EtherTW
Logo_url:https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F890461611575582720%2FeTAoJWB_.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Feth_taipei&tbnid=4aPIMNczidN2cM&vet=12ahUKEwj98Yfz8p3tAhXiGKYKHQEmCkgQMygAegUIARCbAQ..i&docid=NI_JqCLhDD_S-M&w=512&h=512&q=taipei%20ethereum&ved=2ahUKEwj98Yfz8p3tAhXiGKYKHQEmCkgQMygAegUIARCbAQ
Tags: community

**Comment by zengmi2140** [comment]
已添加，感谢！
