### ISSUE TITLE
[improvement] change the language prompt in the main page

### ISSUE THREAD

**Issue by bobjiang** [SparkPoolOfficial/eth123.org#6]
首页的语言，一般逻辑是所见即所得。比如显示中文，代表当前是中文页面。

建议修改。
![image](https://user-images.githubusercontent.com/1224604/100240498-97d21380-2f6d-11eb-83f7-e3a909c020c3.png)

**Comment by zengmi2140** [comment]
我们的思路是，如果只能读懂英文的人第一次打开的是中文网页，则可通过右上角切换为英文版。若中文网页右上角写的“中文”，无法读懂中文的用户很难找到切换入口。
