### ISSUE TITLE
Add TokenPocket wallet

### ISSUE THREAD

**Issue by chendatony31** [SparkPoolOfficial/eth123.org#7]
Title: TokenPocket
Desc: multi-chain wallet
Website: https://tokenpocket.pro/
Logo_url: https://tp-statics.tokenpocket.pro/logo/tpt-logo.png
Tags:  wallet

**Comment by zengmi2140** [comment]
感谢您提供的信息！我们网站目前暂时只选择以太坊生态的核心钱包进行展示，主要是私钥/插件/网页钱包以及最近兴起的智能钱包。对于泛区块行业的全币种钱包，由于数量众多，目前暂不展示，后续若开放展示会添加您提交的项目，感谢！
