### ISSUE TITLE
Add CoFiX

### ISSUE THREAD

**Issue by zhangzhongnan928** [SparkPoolOfficial/eth123.org#8]
Title: CoFiX
Desc: A Computable On-Chain Market Making Protocol.
Website: https://cofix.io/
Logo_url: https://drive.google.com/file/d/1JJv0oGCj2P9uRVXoB77pmR4jKY5DCBco/view?usp=sharing
Tags:  #DEX

**Comment by zengmi2140** [comment]
已添加
